# Generated by Django 3.2.13 on 2022-06-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='binance', max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('price_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('volume_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screener.exchange')),
            ],
        ),
    ]
