# Generated by Django 3.2.13 on 2022-06-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
            ],
        ),
    ]
