# Generated by Django 3.2.13 on 2022-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(blank=True, default='binance', max_length=20, null=True)),
                ('symbol_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('last_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pair',
            name='exchange',
        ),
        migrations.DeleteModel(
            name='Exchange',
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
    ]
