export const ADD_TICKER_REQUEST = "ADD_TICKER_REQUEST"
export const ADD_TICKER_SUCCESS = "ADD_TICKER_SUCCESS"
export const ADD_TICKER_FAIL = "ADD_TICKER_FAIL"
export const TICKERS_UPDATING = "TICKERS_UPDATING"
export const TICKERS_UPDATED = "TIKCERS_UPDATED"

